// AUTO-GENERATED by scripts/gen-sample-data.js — DO NOT EDIT

// Define a type for the structure of your sample data
export interface SampleData {
  [key: string]: Array<Record<string, any>>; // Each key maps to an array of objects
}

export const sampleData: SampleData = {
  "tenants": [
    {
      "id": "tenant-231",
      "name": "Provision Corp",
      "email": "contact@provision.com",
      "password": "hashedpassword1",
      "remember_token": "token123",
      "phone": "123-456-7890",
      "address": "123 Main St, Anytown",
      "created_at": "2025-06-30T20:40:58.830Z",
      "updated_at": "2025-07-01T04:19:09.158Z"
    },
    {
      "id": "tenant-748",
      "name": "Management Solutions",
      "email": "info@management.com",
      "password": "hashedpassword2",
      "remember_token": "token456",
      "phone": "098-765-4321",
      "address": "456 Oak Ave, Otherville",
      "created_at": "2025-06-30T18:47:36.323Z",
      "updated_at": "2025-07-01T04:40:35.633Z"
    },
    {
      "id": "tenant-886",
      "name": "Hydrocarbon Bistro",
      "email": "sales@hydrocarbon.com",
      "password": "hashedpassword3",
      "remember_token": "token789",
      "phone": "555-111-2222",
      "address": "789 Pine Ln, Sometown",
      "created_at": "2025-06-30T15:35:37.178Z",
      "updated_at": "2025-07-01T04:21:39.067Z"
    }
  ],
  "domains": [
    {
      "id": "domain-758",
      "tenant_id": "tenant-231",
      "domain": "provision.com",
      "is_primary": true,
      "created_at": "2025-06-30T18:39:55.760Z",
      "updated_at": "2025-07-01T05:03:39.558Z"
    },
    {
      "id": "domain-485",
      "tenant_id": "tenant-748",
      "domain": "management.net",
      "is_primary": false,
      "created_at": "2025-06-30T16:23:16.939Z",
      "updated_at": "2025-07-01T02:15:56.744Z"
    }
  ],
  "jobs": [
    {
      "id": "job-254",
      "queue": "email_queue",
      "payload": "{\"user_id\": \"user-1\", \"type\": \"welcome_email\"}",
      "attempts": 1,
      "reserved_at": "2025-06-30T15:04:04.167Z",
      "available_at": "2025-07-01T07:24:14.656Z",
      "created_at": "2025-07-01T10:35:19.574Z"
    }
  ],
  "failed_jobs": [
    {
      "id": "failed-job-557",
      "uuid": "uuid-12345",
      "connection": "redis",
      "queue": "payment_queue",
      "payload": "{\"order_id\": \"order-101\"}",
      "exception": "PaymentGatewayError",
      "failed_at": "2025-06-30T15:27:48.238Z"
    }
  ],
  "password_resets": [
    {
      "email": "user1@example.com",
      "token": "resettoken1",
      "created_at": "2025-06-30T23:43:57.480Z"
    }
  ],
  "users": [
    {
      "id": "user-649",
      "name": "Alice Smith",
      "email": "alice@example.com",
      "email_verified_at": "2025-07-01T08:37:59.718Z",
      "password": "hashedpasswordA",
      "remember_token": "rememberA",
      "created_at": "2025-07-01T08:37:59.718Z",
      "updated_at": "2025-07-01T09:24:06.863Z",
      "cashAccounts": "CASH001",
      "cardAccounts": "CARD001",
      "onlineAccounts": "ONLINE001",
      "gpayAccounts": "GPAY001",
      "phonepeAccounts": "PHONEPE001",
      "amazonpayAccounts": "AMAZONPAY001",
      "locations": "Main Store"
    },
    {
      "id": "user-813",
      "name": "Bob Johnson",
      "email": "bob@example.com",
      "email_verified_at": "2025-06-30T14:20:19.561Z",
      "password": "hashedpasswordB",
      "remember_token": "rememberB",
      "created_at": "2025-06-30T14:20:19.561Z",
      "updated_at": "2025-06-30T17:32:14.126Z",
      "cashAccounts": "CASH002",
      "cardAccounts": "CARD002",
      "onlineAccounts": "ONLINE002",
      "gpayAccounts": "GPAY002",
      "phonepeAccounts": "PHONEPE002",
      "amazonpayAccounts": "AMAZONPAY002",
      "locations": "Branch Store"
    }
  ],
  "user_stores": [
    {
      "id": "us-773",
      "user_id": "user-649",
      "store_id": "store-156",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    }
  ],
  "roles": [
    {
      "id": "role-61",
      "name": "Admin",
      "guard_name": "web",
      "description": "Administrator role",
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z"
    },
    {
      "id": "role-101",
      "name": "Cashier",
      "guard_name": "web",
      "description": "Cashier role",
      "created_at": "2025-07-01T03:39:13.125Z",
      "updated_at": "2025-06-30T18:59:10.027Z"
    }
  ],
  "permissions": [
    {
      "id": "perm-737",
      "name": "manage-orders",
      "guard_name": "web",
      "description": "Permission to manage orders",
      "created_at": "2025-06-30T14:59:40.758Z",
      "updated_at": "2025-07-01T03:22:15.158Z"
    }
  ],
  "role_has_permissions": [
    {
      "role_id": "role-61",
      "permission_id": "perm-737"
    }
  ],
  "model_has_permissions": [
    {
      "permission_id": "perm-737",
      "model_type": "App\\Models\\User",
      "model_id": "user-649"
    }
  ],
  "model_has_roles": [
    {
      "role_id": "role-61",
      "model_type": "App\\Models\\User",
      "model_id": "user-649"
    }
  ],
  "products": [ // Assuming these are general inventory products, not menu foods
    {
      "id": "prod-997",
      "tenant_id": "tenant-231",
      "name": "Flour Bag",
      "description": "5kg bag of all-purpose flour",
      "price": 50,
      "stock_quantity": 298,
      "category_id": "cat-bakery",
      "supplier_id": "sup-61",
      "created_at": "2025-06-30T17:15:22.518Z",
      "updated_at": "2025-06-30T17:34:04.225Z"
    }
  ],
  "purchases": [
    {
      "id": "pur-169",
      "tenant_id": "tenant-231",
      "supplier_id": "sup-61",
      "total_amount": 500,
      "purchase_date": "2025-07-01T00:09:44.209Z",
      "status": "completed",
      "notes": "Bulk order for flour",
      "created_at": "2025-07-01T07:23:40.857Z",
      "updated_at": "2025-06-30T19:15:58.219Z"
    }
  ],
  "purchase_items": [
    {
      "id": "puri-551",
      "purchase_id": "pur-169",
      "food_id": "food-743", // Link to a food item
      "quantity": 10,
      "price": 50,
      "sub_total": 500,
      "created_at": "2025-06-30T17:15:22.518Z",
      "updated_at": "2025-06-30T17:34:04.225Z"
    }
  ],
  "refunds": [
    {
      "id": "ref-743",
      "order_id": "order-743",
      "customer_id": "cust-156",
      "amount": 100,
      "reason": "Customer dissatisfied",
      "refund_date": "2025-06-30T22:05:27.430Z",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    }
  ],
  "refund_items": [
    {
      "id": "refi-743",
      "refund_id": "ref-743",
      "food_id": "food-743", // Link to a food item
      "quantity": 1,
      "price": 100,
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    }
  ],
  "shifts": [
    {
      "id": "shift-156",
      "employee_id": "user-649", // Link to a user/employee
      "start_time": "2025-07-01T06:45:15.231Z",
      "end_time": "2025-07-01T14:45:15.231Z",
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z"
    }
  ],
  "stock_adjustments": [
    {
      "id": "sa-737",
      "stock_id": "stock-743", // Link to a stock item
      "quantity_change": -5,
      "reason": "Spoilage",
      "adjustment_date": "2025-06-30T14:59:40.758Z",
      "created_at": "2025-06-30T14:59:40.758Z",
      "updated_at": "2025-07-01T03:22:15.158Z"
    }
  ],
  "suppliers": [
    {
      "id": "sup-61",
      "name": "Global Food Supplies",
      "contact_person": "Mr. John Doe",
      "phone": "111-222-3333",
      "email": "john.doe@globalfood.com",
      "address": "100 Supply Rd, Supplytown",
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z"
    }
  ],
  "taxes": [
    {
      "id": "tax-737",
      "name": "VAT 15%",
      "percentage": 15,
      "is_active": true,
      "created_at": "2025-06-30T14:59:40.758Z",
      "updated_at": "2025-07-01T03:22:15.158Z"
    }
  ],
  "transactions": [
    {
      "id": "tran-743",
      "order_id": "order-743",
      "payment_method": "Card",
      "amount": 100,
      "transaction_date": "2025-06-30T22:05:27.430Z",
      "status": "completed",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    }
  ],
  "loyalty_points": [
    {
      "id": "lp-156",
      "customer_id": "cust-156",
      "points_earned": 50,
      "points_redeemed": 0,
      "date": "2025-07-01T06:45:15.231Z",
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z"
    }
  ],
  "discounts": [
    {
      "id": "disc-737",
      "name": "Summer Sale",
      "code": "SUMMER10",
      "type": "percentage",
      "value": 10, // 10%
      "min_order_amount": 50,
      "max_discount_amount": 20,
      "usage_limit": 100,
      "expiry_date": "2025-08-31T23:59:59.000Z",
      "is_active": true,
      "created_at": "2025-06-30T14:59:40.758Z",
      "updated_at": "2025-07-01T03:22:15.158Z"
    }
  ],
  "payments": [
    {
      "id": "pay-743",
      "order_id": "order-743",
      "amount": 100,
      "method": "Card", // Changed from 'method' to 'payment_method' in entities
      "transaction_id": "transid123",
      "payment_date": "2025-06-30T22:05:27.430Z",
      "status": "completed",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    }
  ],
  "invoices": [
    {
      "id": "inv-156",
      "order_id": "order-743",
      "invoice_number": "INV-2025-001",
      "total_amount": 100,
      "invoice_date": "2025-07-01T06:45:15.231Z",
      "status": "paid",
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z",
      "tax_amount": 10,
      "discount_amount": 0,
      "customer_id": "cust-156"
    }
  ],
  "kitchens": [
    {
      "id": "kitchen-737",
      "name": "Main Kitchen",
      "description": "Primary kitchen for all food preparation",
      "created_at": "2025-06-30T14:59:40.758Z",
      "updated_at": "2025-07-01T03:22:15.158Z"
    }
  ],
  "menus": [
    {
      "id": "menu-61",
      "name": "Main Menu",
      "description": "Standard daily menu",
      "is_active": true,
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z"
    }
  ],
  "notifications": [
    {
      "id": "notif-737",
      "user_id": "user-649",
      "title": "New Order Received",
      "message": "Order #743 has been placed.",
      "type": "info",
      "is_read": false,
      "created_at": "2025-06-30T14:59:40.758Z",
      "updated_at": "2025-07-01T03:22:15.158Z"
    }
  ],
  "foods": [
    {
      "id": "food-743",
      "name": "Classic Burger",
      "category_id": "1",
      "brand_id": "brand-A",
      "unit_id": "unit-pc",
      "purchase_price": 50,
      "sale_price": 100,
      "description": "A delicious burger with special sauce.",
      "image": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "is_active": true,
      "is_featured": true,
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z",
      "code": "BGB001",
      "hsn": "HSN123",
      "cost": 40,
      "price_include_gst": false,
      "cost_include_gst": true,
      "gst_percentage": 10,
      "food_category_id": "cat-burger",
      "food_brand_id": "brand-A",
      "created_by": "admin",
      "updated_by": "admin",
      "kitchen_id": "kitchen-737",
      "price": 100 // Ensure price is present for API enrichment
    },
    {
      "id": "food-269",
      "name": "Scabies Fries", // Renamed for clarity
      "category_id": "cat-sides",
      "brand_id": "brand-B",
      "unit_id": "unit-g",
      "purchase_price": 20,
      "sale_price": 50,
      "description": "Crispy golden fries.",
      "image": "scabies_fries.jpg",
      "is_active": true,
      "is_featured": false,
      "created_at": "2025-06-30T14:30:32.350Z",
      "updated_at": "2025-06-30T12:11:28.951Z",
      "code": "FRS001",
      "hsn": "HSN124",
      "cost": 15,
      "price_include_gst": true,
      "cost_include_gst": false,
      "gst_percentage": 10,
      "food_category_id": "cat-sides",
      "food_brand_id": "brand-B",
      "created_by": "admin",
      "updated_by": "admin",
      "kitchen_id": "kitchen-737",
      "price": 50 // Ensure price is present for API enrichment
    },
    {
      "id": "food-490",
      "name": "Pavement Pizza", // Renamed for clarity
      "category_id": "cat-pizza",
      "brand_id": "brand-C",
      "unit_id": "unit-pc",
      "purchase_price": 80,
      "sale_price": 150,
      "description": "Large pepperoni pizza.",
      "image": "pavement_pizza.jpg",
      "is_active": true,
      "is_featured": true,
      "created_at": "2025-06-30T13:34:09.476Z",
      "updated_at": "2025-07-01T10:48:33.081Z",
      "code": "PZ001",
      "hsn": "HSN125",
      "cost": 70,
      "price_include_gst": false,
      "cost_include_gst": true,
      "gst_percentage": 10,
      "food_category_id": "cat-pizza",
      "food_brand_id": "brand-C",
      "created_by": "admin",
      "updated_by": "admin",
      "kitchen_id": "kitchen-737",
      "price": 150 // Ensure price is present for API enrichment
    },
    {
      "id": "food-907",
      "name": "Quiver Quinoa Salad", // Renamed for clarity
      "category_id": "cat-salad",
      "brand_id": "brand-D",
      "unit_id": "unit-bowl",
      "purchase_price": 40,
      "sale_price": 80,
      "description": "Healthy quinoa salad with fresh veggies.",
      "image": "quiver_salad.jpg",
      "is_active": true,
      "is_featured": false,
      "created_at": "2025-06-30T16:32:00.842Z",
      "updated_at": "2025-07-01T08:24:47.113Z",
      "code": "SAL001",
      "hsn": "HSN126",
      "cost": 30,
      "price_include_gst": true,
      "cost_include_gst": false,
      "gst_percentage": 10,
      "food_category_id": "cat-salad",
      "food_brand_id": "brand-D",
      "created_by": "admin",
      "updated_by": "admin",
      "kitchen_id": "kitchen-737",
      "price": 80 // Ensure price is present for API enrichment
    },
    {
      "id": "food-616",
      "name": "Horse Hotdog", // Renamed for clarity
      "category_id": "cat-hotdog",
      "brand_id": "brand-E",
      "unit_id": "unit-pc",
      "purchase_price": 30,
      "sale_price": 60,
      "description": "Classic hotdog with all the fixings.",
      "image": "horse_hotdog.jpg",
      "is_active": true,
      "is_featured": false,
      "created_at": "2025-07-01T10:28:05.607Z",
      "updated_at": "2025-06-30T21:14:27.304Z",
      "code": "HDG001",
      "hsn": "HSN127",
      "cost": 25,
      "price_include_gst": false,
      "cost_include_gst": true,
      "gst_percentage": 10,
      "food_category_id": "cat-hotdog",
      "food_brand_id": "brand-E",
      "created_by": "admin",
      "updated_by": "admin",
      "kitchen_id": "kitchen-737",
      "price": 60 // Ensure price is present for API enrichment
    }
  ],
  "tables": [
    {
      "id": "table-743",
      "name": "Table 1",
      "code": "T1",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z",
      "status": "occupied",
      "current_order_id": "order-743"
    },
    {
      "id": "table-269",
      "name": "Table 2",
      "code": "T2",
      "created_at": "2025-06-30T14:30:32.350Z",
      "updated_at": "2025-06-30T12:11:28.951Z",
      "status": "available",
      "current_order_id": null
    },
    {
      "id": "table-490",
      "name": "Table 3",
      "code": "T3",
      "created_at": "2025-06-30T13:34:09.476Z",
      "updated_at": "2025-07-01T10:48:33.081Z",
      "status": "occupied",
      "current_order_id": "order-490"
    }
  ],
  "orders": [
    {
      "id": "order-743",
      "tenant_id": "tenant-231",
      "table_id": "table-743",
      "customer_id": "cust-156",
      "total_amount": 200.00,
      "status": "preparing",
      "notes": "No onions on burger",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z",
      "subtotal_amount": 150.00,
      "tax_amount": 15.00,
      "discount_amount": 0.00,
      "employee_id": "user-649",
      "order_type": "dine-in"
    },
    {
      "id": "order-269",
      "tenant_id": "tenant-748",
      "table_id": null, // Takeaway
      "customer_id": null, // Walk-in
      "total_amount": 50.00,
      "status": "new",
      "notes": "Customer waiting",
      "created_at": "2025-06-30T14:30:32.350Z",
      "updated_at": "2025-06-30T12:11:28.951Z",
      "subtotal_amount": 50.00,
      "tax_amount": 5.00,
      "discount_amount": 0.00,
      "employee_id": "user-813",
      "order_type": "takeaway"
    },
    {
      "id": "order-490",
      "tenant_id": "tenant-886",
      "table_id": "table-490",
      "customer_id": "cust-876",
      "total_amount": 150.00,
      "status": "ready",
      "notes": "Extra crispy crust",
      "created_at": "2025-06-30T13:34:09.476Z",
      "updated_at": "2025-07-01T10:48:33.081Z",
      "subtotal_amount": 150.00,
      "tax_amount": 15.00,
      "discount_amount": 0.00,
      "employee_id": "user-649",
      "order_type": "dine-in"
    }
  ],
  "order_items": [
    {
      "id": "oi-743-1",
      "order_id": "order-743",
      "food_id": "food-743", // Blossom Burger
      "quantity": 1,
      "price": 100,
      "sub_total": 100,
      "notes": "No pickles",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    },
    {
      "id": "oi-743-2",
      "order_id": "order-743",
      "food_id": "food-269", // Scabies Fries
      "quantity": 1,
      "price": 50,
      "sub_total": 50,
      "notes": "",
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    },
    {
      "id": "oi-269-1",
      "order_id": "order-269",
      "food_id": "food-269", // Scabies Fries
      "quantity": 1,
      "price": 50,
      "sub_total": 50,
      "notes": "Extra salty",
      "created_at": "2025-06-30T14:30:32.350Z",
      "updated_at": "2025-06-30T12:11:28.951Z"
    },
    {
      "id": "oi-490-1",
      "order_id": "order-490",
      "food_id": "food-490", // Pavement Pizza
      "quantity": 1,
      "price": 150,
      "sub_total": 150,
      "notes": "",
      "created_at": "2025-06-30T13:34:09.476Z",
      "updated_at": "2025-07-01T10:48:33.081Z"
    }
  ],
  "menu_items": [ // Linking Menu to Food
    {
      "id": "mi-743",
      "menu_id": "menu-61",
      "food_id": "food-743", // Blossom Burger
      "position": 1,
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    },
    {
      "id": "mi-269",
      "menu_id": "menu-61",
      "food_id": "food-269", // Scabies Fries
      "position": 2,
      "created_at": "2025-06-30T14:30:32.350Z",
      "updated_at": "2025-06-30T12:11:28.951Z"
    }
  ],
  "categories": [
    {
      "id": 1,
      "name": "Appetizers",
      "code": "APP",
      "image": "https://cdn-icons-png.flaticon.com/512/1069/1069354.png",
      "created_at": "2025-07-01T09:00:00Z",
      "updated_at": "2025-07-01T09:00:00Z"
    },
    {
      "id": 2,
      "name": "Main Courses",
      "code": "MAIN",
      "image": "https://cdn3.iconfinder.com/data/icons/wedding-276/512/Food-1024.png",
      "created_at": "2025-07-01T09:05:00Z",
      "updated_at": "2025-07-01T09:05:00Z"
    },
    {
      "id": 3,
      "name": "Desserts",
      "code": "DESSERT",
      "image": "https://cdn2.iconfinder.com/data/icons/sweets-2-filled/64/dessert-16-1024.png",
      "created_at": "2025-07-01T09:10:00Z",
      "updated_at": "2025-07-01T09:10:00Z"
    },
    {
      "id": 4,
      "name": "Beverages",
      "code": "BEV",
      "image": "https://cdn-icons-png.flaticon.com/512/6190/6190582.png",
      "created_at": "2025-07-01T09:15:00Z",
      "updated_at": "2025-07-01T09:15:00Z"
    },
    {
      "id": 5,
      "name": "Salads",
      "code": "SALAD",
      "image": "https://i.pinimg.com/originals/03/08/4b/03084b165106d2df9310fede29283b40.png",
      "created_at": "2025-07-01T09:20:00Z",
      "updated_at": "2025-07-01T09:20:00Z"
    }
  ],
  "customers": [
    {
      "id": "cust-156",
      "name": "John Customer",
      "address": "10 Customer St",
      "area": "Downtown",
      "tax_number": "TAX12345",
      "district": "Central",
      "phone": "555-123-4567",
      "points": 150,
      "no_points": 0,
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z"
    },
    {
      "id": "cust-876",
      "name": "Jane Doe",
      "address": "20 Doe Rd",
      "area": "Uptown",
      "tax_number": "TAX67890",
      "district": "North",
      "phone": "555-987-6543",
      "points": 200,
      "no_points": 0,
      "created_at": "2025-07-01T07:11:21.033Z",
      "updated_at": "2025-06-30T16:47:33.268Z"
    }
  ],
  "employees": [ // Adjusted to match User interface from entities.ts
    {
      "id": "emp-61",
      "name": "Sarah Server",
      "email": "sarah@example.com",
      "phone": "555-100-2000",
      "role_id": "role-101", // Cashier role
      "hire_date": "2024-01-15T00:00:00.000Z",
      "salary": 3000,
      "created_at": "2025-07-01T06:45:15.231Z",
      "updated_at": "2025-06-30T15:02:50.627Z"
    },
    {
      "id": "emp-101",
      "name": "Mike Manager",
      "email": "mike@example.com",
      "phone": "555-300-4000",
      "role_id": "role-61", // Admin role
      "hire_date": "2023-05-20T00:00:00.000Z",
      "salary": 5000,
      "created_at": "2025-07-01T03:39:13.125Z",
      "updated_at": "2025-06-30T18:59:10.027Z"
    }
  ],
  "expense_categories": [
    {
      "id": "expcat-1",
      "name": "Utilities",
      "description": "Electricity, water, gas bills",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "expenses": [
    {
      "id": "exp-1",
      "category_id": "expcat-1",
      "amount": 250.75,
      "description": "Monthly electricity bill",
      "expense_date": "2025-07-15T00:00:00.000Z",
      "created_at": "2025-07-15T00:00:00.000Z",
      "updated_at": "2025-07-15T00:00:00.000Z",
      "tenant_id": "tenant-231"
    }
  ],
  "units": [
    {
      "id": "unit-pc",
      "name": "Piece",
      "short_name": "pc",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    },
    {
      "id": "unit-g",
      "name": "Gram",
      "short_name": "g",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "stocks": [
    {
      "id": "stock-743",
      "food_id": "food-743",
      "quantity": 100,
      "unit_id": "unit-pc",
      "purchase_price": 50,
      "sale_price": 100,
      "created_at": "2025-06-30T22:05:27.430Z",
      "updated_at": "2025-07-01T02:25:49.986Z"
    },
    {
      "id": "stock-269",
      "food_id": "food-269",
      "quantity": 200,
      "unit_id": "unit-g",
      "purchase_price": 20,
      "sale_price": 50,
      "created_at": "2025-06-30T14:30:32.350Z",
      "updated_at": "2025-06-30T12:11:28.951Z"
    }
  ],
  "store_timings": [
    {
      "id": "st-1",
      "store_id": "store-156", // Assuming a store ID
      "day_of_week": "Monday",
      "opening_time": "09:00",
      "closing_time": "22:00",
      "is_closed": false,
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "tables_sections": [
    {
      "id": "ts-1",
      "name": "Main Dining Area",
      "description": "Section for general dining tables",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "coupons": [
    {
      "id": "coup-737",
      "code": "SAVE10",
      "type": "percentage",
      "value": 10,
      "min_order_amount": 50,
      "max_discount_amount": 20,
      "usage_limit": 100,
      "expiry_date": "2025-12-31T23:59:59.000Z",
      "is_active": true,
      "created_at": "2025-06-30T14:59:40.758Z",
      "updated_at": "2025-07-01T03:22:15.158Z"
    }
  ],
  "table_coupons": [
    {
      "id": "tc-1",
      "table_id": "table-743",
      "coupon_id": "coup-737",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "product_coupons": [
    {
      "id": "pc-1",
      "food_id": "food-743",
      "coupon_id": "coup-737",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "customer_coupons": [
    {
      "id": "cc-1",
      "customer_id": "cust-156",
      "coupon_id": "coup-737",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "reviews": [
    {
      "id": "rev-1",
      "customer_id": "cust-156",
      "food_id": "food-743",
      "rating": 5,
      "comment": "Absolutely delicious!",
      "review_date": "2025-07-18T10:00:00.000Z",
      "created_at": "2025-07-18T10:00:00.000Z",
      "updated_at": "2025-07-18T10:00:00.000Z"
    }
  ],
  "faqs": [
    {
      "id": "faq-1",
      "question": "Do you offer vegetarian options?",
      "answer": "Yes, we have a wide range of vegetarian dishes.",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "invoice_items": [
    {
      "id": "invi-1",
      "invoice_id": "inv-156",
      "food_id": "food-743",
      "quantity": 1,
      "price": 100,
      "sub_total": 100,
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "payrolls": [
    {
      "id": "pay-1",
      "employee_id": "emp-61",
      "month": "July",
      "year": 2025,
      "basic_salary": 2500,
      "allowances": 500,
      "deductions": 100,
      "net_salary": 2900,
      "payment_date": "2025-07-20T00:00:00.000Z",
      "created_at": "2025-07-20T00:00:00.000Z",
      "updated_at": "2025-07-20T00:00:00.000Z"
    }
  ],
  "administrators": [
    {
      "id": "admin-1",
      "user_id": "user-649",
      "role": "Super Admin",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "announcements": [
    {
      "id": "ann-1",
      "title": "New Menu Items!",
      "content": "Exciting new dishes added to our menu, check them out!",
      "published_at": "2025-07-15T00:00:00.000Z",
      "expires_at": "2025-08-15T00:00:00.000Z",
      "created_at": "2025-07-15T00:00:00.000Z",
      "updated_at": "2025-07-15T00:00:00.000Z"
    }
  ],
  "settings": [
    {
      "id": "set-1",
      "key": "tax_rate",
      "value": "0.10",
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "carts": [
    {
      "id": "cart-1",
      "customer_id": "cust-156",
      "created_at": "2025-07-20T00:00:00.000Z",
      "updated_at": "2025-07-20T00:00:00.000Z"
    }
  ],
  "cart_items": [
    {
      "id": "ci-1",
      "cart_id": "cart-1",
      "food_id": "food-743",
      "quantity": 1,
      "price": 100,
      "created_at": "2025-07-20T00:00:00.000Z",
      "updated_at": "2025-07-20T00:00:00.000Z"
    }
  ],
  "delivery_personnels": [
    {
      "id": "dp-1",
      "name": "Delivery Dave",
      "phone": "555-DELIVER",
      "vehicle_details": "Motorbike ABC123",
      "is_available": true,
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "wallets": [
    {
      "id": "wallet-1",
      "customer_id": "cust-156",
      "balance": 500,
      "created_at": "2025-07-01T00:00:00.000Z",
      "updated_at": "2025-07-01T00:00:00.000Z"
    }
  ],
  "coupon_redemptions": [
    {
      "id": "cr-1",
      "coupon_id": "coup-737",
      "customer_id": "cust-156",
      "order_id": "order-743",
      "redemption_date": "2025-07-19T00:00:00.000Z",
      "discount_amount": 10,
      "created_at": "2025-07-19T00:00:00.000Z",
      "updated_at": "2025-07-19T00:00:00.000Z"
    }
  ],
  "cash_flows": [
    {
      "id": "cf-1",
      "source_type": "Sale",
      "source_id": "order-743",
      "amount": 200,
      "type": "inflow",
      "description": "Sale of Order #743",
      "flow_date": "2025-07-20T00:00:00.000Z",
      "created_at": "2025-07-20T00:00:00.000Z",
      "updated_at": "2025-07-20T00:00:00.000Z"
    }
  ],
  "password_changes": [
    {
      "id": "pc-1",
      "user_id": "user-649",
      "changed_at": "2025-07-10T00:00:00.000Z"
    }
  ],
  "stocks_movements": [
    {
      "id": "sm-1",
      "stock_id": "stock-743",
      "type": "out",
      "quantity": 1,
      "movement_date": "2025-07-20T00:00:00.000Z",
      "notes": "Used for Order #743",
      "created_at": "2025-07-20T00:00:00.000Z",
      "updated_at": "2025-07-20T00:00:00.000Z"
    }
  ],
  "contact_messages": [
    {
      "id": "cm-1",
      "name": "Customer Inquiry",
      "email": "customer@example.com",
      "subject": "Feedback on service",
      "message": "The service was excellent!",
      "created_at": "2025-07-19T00:00:00.000Z",
      "updated_at": "2025-07-19T00:00:00.000Z"
    }
  ]
};
